src/home/home.scss
- Gave the text full width, to eliminate the white-space between text and image as suggested in this [issue](https://www.notion.so/curvelabs/Close-the-Gap-between-Fair-Launches-Image-Text-1ce5060974984fdfa98849c49df3eb4c)
- Though not explicitly requested in Figma, I think it makes sense to add a border-radius to the image to keep it consistent with the rest of the elements/design.
=> Fix gap between image and text

src/newSeed/baseStage.scss, src/newSeed/stage5.html, src/resources/elements/questionMark/questionMark.scss, src/styles/styles.scss
- Aligned the question mark vertically to the center- [issue](https://www.notion.so/curvelabs/Seed-Reg-Stage-2-Question-Marks-should-be-centered-7b0a85fa682049a88e9f52135c9cfc77)
- Added `Optional` place holder to the text area in stage 5 - [issue](https://www.notion.so/curvelabs/Seed-Reg-make-placeholders-consistent-in-wording-wrt-optional-31472724fbfa43d68e5ce4a6c95a2bcb)
- Added 12px padding inside text areas also from the top and bottom to keep it visually persistent with the other input boxes:
=> Seed registration modifications

src/newSeed/stage4.html
This is part of the following [Issue](https://www.notion.so/curvelabs/Seed-Wizards-Page-4-Change-Tool-Tip-Texts-09a4703aadd341cb84d0dd77fff01998)
Fixed the typo in Koria->North Korea.
Text for `Whitelist` needs more clarification with @dkent600- 
What are the file types: `.xx and .xx formats` the file should be in?
=> fixed typo

src/newSeed/baseStage.scss
The gray color, which should apply the _characters counter_, was applied to the whole `category` label element. I've moved the declaration to the `span` element containing this counter.
=> remove category color inherit from the wrong class

src/home/home.scss
Closed the gap between `Never miss a launch` and `Sign-up for the Prime Launch Newsletter...` in the homepage.
Closes this [issue](https://www.notion.so/curvelabs/close-the-gap-between-Never-miss-a-launch-and-sign-up-for-the-prime-launch-newsletter-627007453c4b491ba102553b51b13c4e)
=> remove gap between title and text

src/newSeed/baseStage.scss, src/newSeed/stage6.html
The grid column has now auto width instead of fixed `fr`.
Removed the `projectLogo` class and moved its declarations to `tokenInfo` since it applies to both _Project Details_ and _Seed Details_.
Although `projectLogo` has now one extra column, I believe it is not an issue.
This fix refers to the following [issue](https://www.notion.so/curvelabs/Section-for-the-Token-Name-should-have-more-width-ec390c6a9dc1444cba141e58845b2622)
=> fix token name width

src/seedDashboard/seedDashboard.html, src/seedDashboard/seedDashboard.scss
- Padding to the left was removed.
- Added top padding to align sub description to the center of the button. 
Closes this [issue](https://www.notion.so/curvelabs/Check-Eligibility-should-be-aligned-with-Subtext-5272a87913ea4c19a809713ec2ee652d)
=> removed padding from subtext to align with header

src/home/home.scss
Just find out that this `width` declaration on screen resolution width between 397px and 420px, caused to difference in buttons width:
I guess this media query can be removed now.
=> removed unnecessary width declaration on mobile

src/newSeed/stage4.html, src/resources/dialogs/disclaimer/disclaimer.html, src/styles/styles.scss
Apparently the -webkit-text-fill-color: transparent; is what’s failing in Safari, but only when used with a button tag. Once I change the button into a div tag (and set it to inline-block) it functions and looks correctly on chrome/safari/opera/edge/brave/firefox browsers.
I found this [issue](https://www.notion.so/curvelabs/Disclaimer-DECLINE-button-text-is-not-visible-in-Safari-16ef63b72fa0480296dedd79744cd998) affecting both the disclaimer and the stage4 page of the wizard.
=> Disclaimer decline button text is not visible in Safari

src/resources/dialogs/disclaimer/disclaimer.html, src/styles/styles.scss
Fixed the accept button to have the same width as the decline button.
I have returned the accept `button` to be a native `button` element, as this is the most simple way to maintain the 'disabled' state that was lost too when converted into `div`.
I've added the two declarations:
```
display: inline-block;
margin: 5px 0 5px 5px;
```
they defined for the native `button` and should have been translated to the `div`-button too.
=> fix disclaimer accept button too wide

src/selectPackage/selectPackage.html
This PR fixes the button behavior on the `Select Package` page- Should be a button and not a link.
Closes Issue #193.
=> converted link into a button

src/seedAdminDashboard/seedAdminDashboard.html, src/seedAdminDashboard/seedAdminDashboard.ts
Optional:
If we want to not display drop down only when the user have created only single seed.
But if the admin have created multiple seed, we display a drop down. It doesn't matter if they access using `admin/seeds/dashboard` or `admin/seeds/dashboard/0x9f13D7D0cc9f4f5555cc34Ce6AB49c0bbD0c2f4f`. They should see a drop down.
Only if this functionality was intended.
=> Chore: admin allow drop down

src/resources/elements/tokenSelect/tokenSelect.html, src/resources/elements/tokenSelect/tokenSelect.scss
See #245 
Looking at common UI's, might make sense to refactor the drop down to have a `loading` state, and replace the spinner with the `arrow` icon on the right, while loading.
Currently it's impossible to implement since the loading state applies only to the `select-token` element.
Suggested as an optional change...
=> nicer spinny icon for token select dropdown

src/selectPackage/selectPackage.html, src/selectPackage/selectPackage.scss
I guess it makes more sense to use the native `check-circle` icon rather then trying to correctly position the `check` icon in a costum circle.
In case we need to use `.noCheck`- the correct icon will be `time-circle.
See #241
=> Tick Symbol should be a bit smaller

src/newLaunch/launch.scss, src/resources/elements/circledNumber/circledNumber.scss
Missed this fix on mobile view in last PR - On mobile the rulers was still a little off.
In addition, the following changes have been done:
* Converted `em`s to `px`.
* Made the circle round - w+h: 40px.
* A little cleanup for CSS.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
<p>
</p>
<p>
</p>
</td>
<td>
<p>
</p>
<p>
</p>
</td>
</tr>
</table>
=> 364- Sidebar Lines need to be centered

src/newLaunch/lbp/stages/stage4.html
The Vesting Date's additional container has been removed now.
=> Remove vestingDateContainer to fix the vertical align bug

src/seedDashboard/seedDashboard.html
The Seed Dashboard for a particular launches' eligibility card now does not have the mentioned redirection.
=> chore: remove copy for documentation redirect

src/newLaunch/launch.scss
The sidebar numbers' font size is now a bit smaller
New LBP (Desktop)
New LBP (Mobile)
New Seed (Desktop)
New Seed (Mobile)
=> chore: reduce font size over stages numbers

src/resources/dialogs/dialogs.scss, src/resources/dialogs/disclaimer/disclaimer.html, src/styles/styles.scss
Fixes height of "decline" button (.button2)
Align action buttons vertically centered.
Result:
Large screen:
Medium screen:
Small screen:
=> 306- Primedao legal disclaimer button should have the same height

src/services/ProjectTokenHistoricalPriceService.ts
Added `lbpTotalSwapFees(poolId: string): number` method to ProjectTokenHistoricalPriceService.
Pulls the total swap fee from Balancer SubGraph, by the pool-ID.
=> Add Total Swap Fee to The Historical price service

src/lbpDashboard/lbpPriceChart/lbpPriceChart.html, src/lbpDashboard/lbpPriceChart/lbpPriceChart.ts, src/resources/elements/sparkChart/spark-chart.ts, src/services/ProjectTokenHistoricalPriceService.ts
Fixed the chart issue- shows now the trajectory data for launches that haven't started yet.
Added fix to the timescale formatting with the following logic:
Under 24h duration: "H:mm" (5:00)
Under 5 days duration: "MMM DD | H:mm" (Dec 10 | 17:00)
Above 5 days duration: "MMM DD" (Dec 10)
Added Border to the timescale at bottom of the chart (Dashboard only!)
Removed the border from the price scale at the right - Previously, it was in an undefined color. (Coordinated with @renc-curvelabs )
Result: (Mainnet | D2D launch)
=> 653 - Display the preview chart on the lbp dashboard until launch begins

src/launchAbout/launchAbout.scss, src/lbpDashboard/lbpDashboard.scss, src/resources/elements/sparkChart/spark-chart.ts
Fixed width issue with the chart.
Fixed chart not scaling fully on mobile.
Improved form width on smaller screens.
Fixed Admin Dashboard section too wide.
Before <==> Result:
=> 697- Fixed width issues for chart and other elements on the dashboard page

package.json
Added two scripts to `package.json`:
`build-vercel-dev`: Will build a development environment.
`build-vercel-prod`: Will build a production environment 
The environment variable NETWORK should be set up with the required network for the specific build - `rinkeby` | `mainnet` | `arbitrum`.
=> Add build script for vercel

package.json, webpack.config.js
* Cleaned unnecessary build scripts
* Created a simple build script to run on vercel, and is defined by environment variables.
* `PRODUCTION=true` -> builds production env
* `PRODUCTION=false` -> builds development env
* `EXTRACT_CSS=true` -> extracts css
* Added WebPack flags to indicate if `production` and `extractCss` are coming from the `.env` file or from a script parameter.
**NOTE:**
For Vercel to deploy correctly these environment variables are needed:
PRODUCTION=true|false
NETWORK=mainnet|rinkeby|...
EXTRACT_CSS=true|false
=> Unify builds for vercel

package.json
This PR restricts the `Node` version to 14 and above but below 15.
It should fix an issue with Vercels build fails since some dependencies (node-sass) require a `node` version lower than 15.
=> Restrict node version to 14

src/services/EthereumService.ts
Fixed the `getEtherscanLink` function to return the correct explorer URL for each network.
Arbitrum: [https://arbiscan.io](https://arbiscan.io)
Alfajores: [https://alfajores-blockscout.celo-testnet.org](https://alfajores-blockscout.celo-testnet.org)
Celo: [https://explorer.celo.org](https://explorer.celo.org)
Rinkeby (note: set for deprecation): [https://rinkeby.etherscan.io](https://rinkeby.etherscan.io)
Kovan (note: deprecated): [https://kovan.etherscan.io](https://kovan.etherscan.io)
Mainnet: [https://etherscan.io](http://etherscan.io)
=> 785 - Set correct explorer url for each network

src/contracts/celo.json, src/newLaunch/baseStage.ts, src/services/BalancerService.ts, src/services/ProjectTokenHistoricalPriceService.ts
- Updated Celo contract to latest (from this [commit](https://github.com/PrimeDAO/contracts-v2/commit/dcd9f81e990438dedb3cbd78622b3dc9e072357c)). 
Implements new Safe and Signer addresses.
- Updated Celo Safe URL
Support network nuances to the safe URL.
- Updated Celo Subgraph URL
Though LBP-related, it intersects with `adding Celo network` for v1.
- Reused `BalancerService` subgraph URL in the `ProjectTokenHistoricalPriceService`
Small refactor to reduce future risks
=> Updates to celo safe and subgraph

src/admin/seeds/dashboard/dashboard.html
This PR reverts the removal of the following operations from the Admin Dashboard:
- Add Whitelists
- Whitelist an account
- Unwhitelist an account
- The term `Whitelist` is no longer used in V2, and requires a new copy.
- The added functionality origins from V1, and might not comply with the V2 changes.
=> Re-added accidentally removed whitelist operations

src/newLaunch/baseStage.scss, src/newLaunch/permissoned.html, src/newLaunch/seed/config.ts, src/newLaunch/seed/stages/stage4.html, src/newLaunch/seed/stages/stage4.ts, src/newLaunch/seed/stages/stage6.html, src/services/SeedService.ts
Seed config
- feat(seed.config): add isPermissioned prop
- feat(seed.config): add seedTip prop
SeedService
- feat(services): update isPermissioned prop
- feat(services): update where tip is taken from
Wizard Seed Details
- feat(wizard.seedDetails): add permissionedToggle
- feat(wizard.seedDetails): add tipping
Wizard Summary
- feat(wizard.summary): add permissoned toggle
- feat(wizard.summary): take tipping from object
- styles(wizard.summary): cursor:default to toggle
missing sections
added sections, and they should be connected (stage 4 with summary page)
=> sc 760 - wizard seed details: add missing fields

src/admin/seeds/dashboard/dashboard.html, src/admin/seeds/dashboard/dashboard.scss, src/admin/seeds/dashboard/dashboard.ts
Disabled the `Cancel` button if no classes are added.
=> [Admin-Dashboard | sc-1007]: Admin-dashboard-classes-cancel-should-be-disabled

src/admin/seeds/dashboard/dashboard.ts
Fixed: Clicking the `Cancel` button, removes non-deployed classes from the list.
=> [Admin Dashboard | sc-1011]: classes-cancel-should-restore-inisial-state

src/newLaunch/seed/stages/stage7.ts
The tipping value is now added to the `required funding tokens`, instead of the `seed fee`.
=> [Chore / sc-819]: Tipping: Make sure the tip is applied in the correct place (Task 3)

src/newLaunch/seed/stages/stage6.html
Adjusted the date format to `DD-MMM-YYYY`.
(NOTE: I've allowed myself to apply this format to the end-time too, though it wasn't specified in the ticket)
=> [bug/sc-1022]: summary-start-date-date-format-29-jan-2022

src/seedDashboard/seedDashboard.html
Reason: shows funding token, thus can be confusing for user
=> refac(seedDashboard): remove valuation from seedDashboard
