- src/newSeed/baseStage.scss
- src/newSeed/stage2.html
- src/newSeed/stage2.ts
- src/resources/elements/launchSummary/launchSummary.scss
Added an image after the `.infoInput` element.
Added validation for broken links.
Added styling for max width/height of 400px.
Tested on both web/mobile views.
> display image by input of a valid url

- src/newSeed/baseStage.scss
- src/newSeed/stage6.html
- [Fixed the padding for `.summaryContainer`](https://www.notion.so/curvelabs/Seed-Summary-Increase-the-padding-between-sections-7cfbda2d338f40e1bde898a81ee61ba2)
- [Modified text changes](https://www.notion.so/curvelabs/Seed-Summary-Text-Changes-15b657f77f0b49408dc963d2a2501a2a)
> Seed summary modifications

- src/newSeed/stage1.html
Added capitalization to 'Link' in `+ Add Social Media link`
Closes this [issue](https://www.notion.so/curvelabs/Rewording-Add-Social-Media-Link-2b654110eb69454181b6e1069ff0883b)
> added capitalization

- src/home/home.html
- src/home/home.scss
In order to maintain the radius correctly in both mobile and desktop views, I had to take out the `right-margin` from the 'buttons' `contribute` and `launch` and use `gap` instead.
Closes this [Issue](https://www.notion.so/curvelabs/Round-the-Corners-of-Contribute-Apply-for-A-Launch-caaf16503b8848f793b351045e8a45b7)
> made the left-side corneres round too

- src/app.html
- src/app.scss
Added animation to the menu button in mobile view. [issue](https://www.notion.so/curvelabs/Add-Animation-to-the-Hamburger-menu-on-Mobile-3bc1e9a355fc412987e8d8518a8f6468)
> Hamburger menu animation

- src/selectPackage/selectPackage.html
- src/selectPackage/selectPackage.scss
- src/styles/_colors.scss
1. Applied the new copy from @EzraWeller. I have split the description into its own div and gave it a little styling. Closing issue #185.
2. Centered the `Check-Icons` closing issue #191 .
3. Fixed the green color of $AlertGreen. Applied this color to the `Check-Icons`
> Select package copy

- src/resources/elements/dropdown/dropdown.scss
Closes issue #238 
This fix was tested also with the other two instances of the dropdown in the seed registry wizard.
> fix dropdown glitch in admin panel

- src/seedDashboard/seedDashboard.scss
Fixed icons alignment in social media links
> Aligned social icons in links

- src/resources/index.ts
- src/styles/styles.scss
Reverts PrimeDAO/prime-launch-dapp#279
> Revert "Removed unnecessary margin from button"

- src/newLaunch/launchConfig.ts
- src/newLaunch/lbp/config.ts
- src/newLaunch/lbp/stages/stage4.html
- src/newLaunch/lbp/stages/stage4.ts
- src/newLaunch/seed/config.ts
Changing the Legal Disclaimer field in the LBP Wizard stage 4 
from:
into:
> Convert legal disclaimer field into textbox

- src/newLaunch/baseStage.scss
- src/newLaunch/stages/stage1.html
- src/newLaunch/stages/stage2.html
- src/newLaunch/stages/stage3.html
- src/newLaunch/stages/stage5.html
> Align counter vertically to input-box

- src/newLaunch/lbp/stages/stage4.ts
Fix to keep unified with the codebase.
> Refactor casting to number using numberService

- src/newLaunch/lbp/stages/stage4.html
- src/resources/elements/rangeInput/rangeInput.ts
Sets min 2% and max 98% on weight sliders.
Refferst to #388
> 388 - Set min and max weights to sliders

- src/launch/launch.scss
Results => 
Desktop : 
Mobile :
> Launch Page: Request Information link inside Liquid Launch card needs padding

- src/newLaunch/baseStage.scss
- src/newLaunch/stages/stage3.html
> Trash icon should be on third row

- src/newLaunch/lbp/stages/stage4.ts
- src/newLaunch/seed/stages/stage4.ts
> launch admin should be required

- src/newLaunch/seed/stages/stage4.html
Results => 
Desktop version : 
Mobile version :
> Token ratio need adjustments

- src/resources/elements/rangeInput/rangeInput.scss
Results =>
Desktop : 
Mobile :
> Weights feedback need spacing

- src/resources/elements/dropdown/dropdown.scss
- src/resources/elements/dropdown/dropdown.ts
Added fix that closes an opened dropdown if another dropdown is clicked.
Also in this fix:
* z-index change to avoid cross display on animation
* adjusted transition speed to look better when transitioning two dropdowns
> Fix to dropdown won't close while another dropdown is opened

- src/lbpDashboard/lbpDashboardForm/lbpDashboardForm.scss
- src/resources/elements/tokenSelect/tokenSelect.html
- src/resources/elements/tokenSelect/tokenSelect.scss
Fixed also the height differences between the dropdown and the input element and the background slipping out of the dropdown border.
Result:
> 423 - Selected Token Is Clipped By The Dropdown Menu

- src/newLaunch/seed/stages/stage4.ts
> Invalid bignumber value when submitting a new seed

- src/resources/elements/tokenPair/tokenPair.scss
> Add padding in launch cards

- src/newLaunch/baseStage.scss
- src/newLaunch/lbp/elements/launch-preview/launch-preview.html
- src/newLaunch/lbp/stages/stage4.html
> Implementing tooltip and explanation section for lunch details page

- src/seedDashboard/seedDashboard.scss
> Token names not showing in Safari

- aurelia_project/generators/component.ts
- index.ejs
- src/app.ts
- src/home/home.html
- src/launch/launch.html
- src/newLaunch/lbp/stages/stage7.html
- src/newLaunch/seed/stages/stage7.html
- src/newLaunch/stages/stage8.html
- src/newLaunch/stages/submitDisclaimers/submitDisclaimers.html
- src/services/ConsoleLogService.ts
- src/services/DisclaimerService.ts
- src/services/EthereumService.ts
- test/unit/app.spec.ts
> Replace primelaunch by prime launch

- src/selectPackage/selectPackage.html
> Remove seed or liquid launch text

- src/launch/launch.html
> Change launch page subtitle

- src/home/home.html
> Change view all launches to view all

- src/home/home.html
> Change text in apply for launch

- src/home/home.html
> Change title to Seamlessly kickstart your DAO

- src/home/home.html
> Change text home page

- src/navbar/navbar.html
- src/navbar/navbar.scss
- src/navbar/navbar.ts
> Submenu should always be visible

- src/launches/launches.html
> Add N/A at whitelist if no whitelist

- src/navbar/navbar.html
> Change submenu order

- src/launches/launches.scss
> Change ethereum button color

- src/app.ts
- src/documentation/hostALaunch.md
- src/documentation/liquidLaunch.md
- src/documentation/seedLaunch.md
- src/navbar/navbar.html
> Remplace launch by register in the submenu and /launch by /register

- src/home/home.html
> Change contribute to participate

- src/selectPackage/selectPackage.html
> Title should be change according to what is selected seed or lbp

- src/home/home.html
> change subtitle text

- src/services/TokenService.ts
> 500- Launch Preview should display Price Range and market cap if WETH is selected

- src/resources/elements/tokenSelect/tokenSelect.html
> Add space between token name and bracket

- src/lbpDashboard/lbpDashboard.scss
- src/services/LaunchService.ts
- src/services/TokenListService.ts
- src/services/TokenService.ts
Chart width varies, with new media querys.
Form width stays fixed.
> 559 - Chart on the LBP dashboard needs to be visually aligned with the mock

- src/lbpDashboard/lbpDashboardForm/lbpDashboardForm.html
- src/lbpDashboard/projectTokenInfo/projectTokenInfo.html
- src/lbpDashboard/timeRemaining/timeRemaining.html
- src/newLaunch/lbp/elements/launch-preview/launch-preview.html
- src/newLaunch/lbp/stages/stage6.html
- src/newLaunch/seed/stages/stage6.html
> Add commas to numerical fields

- src/newLaunch/baseStage.scss
- src/newLaunch/lbp/stages/stage4.html
> Add separator in wizard stage 4

- src/newLaunch/launchConfig.ts
- src/newLaunch/lbp/stages/stage6.html
- src/newLaunch/seed/stages/stage6.html
- src/newLaunch/stages/stage1.html
- src/newLaunch/stages/stage1.ts
Results =>
Step 1 :
>
Also for step 6 for LBP & Seed :
> Remove project category from seed and lbp wizards

- src/newLaunch/lbp/stages/stage4.html
- src/newLaunch/seed/stages/stage4.html
- src/newLaunch/stages/stage1.html
Results =>
LBP / Seed stage 1: 
LBP stage 4 : 
Seed stage 4 :
> fix: add https in the website plaeholders

- src/newLaunch/lbp/elements/launch-preview/launch-preview.html
- src/newLaunch/lbp/stages/stage4.html
> Modify tooltips and add a new one

- src/launch/launch-box.html
- src/launch/launch.html
- src/selectPackage/selectPackage.html
> Add a link to the documentation

- src/lbpDashboard/projectTokenInfo/projectTokenInfo.ts
Changed the price change percentage in the LBP dashboard, requested in #631
> 631 - Fix to the price change percentage

- src/resources/elements/launchCards/launchCard.scss
- src/resources/elements/timeLeft/timeLeft.scss
> Cards in featured launches for smaller screen need adjustments

- src/entities/LbpManager.ts
- src/lbpDashboard/lbpPriceChart/lbpPriceChart.ts
- src/resources/elements/sparkChart/spark-chart.ts
- src/services/ProjectTokenHistoricalPriceService.ts
> 610- History and forecast lines should start at the same point

- package-lock.json
- package.json
- src/lbpDashboard/lbpDashboardForm/lbpDashboardForm.ts
- src/services/BalancerService.ts
> fix swap limit error

- src/lbpDashboard/lbpPriceChart/lbpPriceChart.ts
- src/services/ProjectTokenHistoricalPriceService.ts
Co-authored-by: Fabian Scherer <fabianschu@users.noreply.github.com>
> Remove chart gap, fixed latest price

- src/lbpDashboard/lbpPriceChart/lbpPriceChart.ts
- src/services/ProjectTokenHistoricalPriceService.ts
This fixes the issue with the average line not starting at the beginning of the chart and also the issue with showing incorrect time at different time zones.
Berlin:
Istanbul:
Works correctly also with uninitialized LBPs:
...and currently running LBPs:
> Fixed avg line and timezone issue

- src/app.scss
- src/navbar/hamburgerMenuButton/hamburgerMenuButton.html
- src/navbar/hamburgerMenuButton/hamburgerMenuButton.scss
- src/navbar/hamburgerMenuButton/hamburgerMenuButton.ts
- src/navbar/mobileMenu/mobileMenu.html
- src/navbar/mobileMenu/mobileMenu.scss
- src/navbar/mobileMenu/mobileMenu.ts
- src/navbar/navbar.html
- src/navbar/navbar.scss
- src/navbar/navbar.ts
Created mobile menu. Available below screen width of 450px.
> 680- Add Hamburger menu to mobile layout

- src/lbpDashboard/timeRemaining/timeRemaining.html
largest -> largest2u
- Might break layout (when eg. token name is too long)
- Cf. comment https://github.com/PrimeDAO/prime-launch-dapp/pull/698#discussion_r773338394
Valid until 23.01: http://localhost:3330/lbp/0x5cb881d6Eddf5966B9a4397a20DdF2b04f44c1EB
> LBP dashboard time remaining: largest -> largest2

- package.json
> add build script for vercel (#730) (#731)

- src/resources/elements/NetworkFeedback/NetworkFeedback.html
Replaced 'Mainnet' text in the network-selector button with 'Ethereum'
> 786 - Fix network name consistency

- src/resources/elements/NetworkFeedback/NetworkFeedback.html
- src/resources/elements/NetworkFeedback/NetworkFeedback.ts
The network selector dropdown should now show the correct network even if previously a local-storage item was set.
> 789 - Fix selector to show correct network for current env

- src/newLaunch/baseStage.scss
- src/newLaunch/seed/stages/stage4.html
added line width limit
added space between text and input
added fullstops at the ends of sentences :/
> Text line width limit

- src/seedSale/seedSale.html
- src/seedSale/seedSale.scss
> class name placeholder

- src/newLaunch/baseStage.scss
- src/newLaunch/seed/stages/stage4.html
- src/newLaunch/seed/stages/stage4.ts
> Sc 309/wizard seeddetails adjust whole seed stage

- src/newLaunch/baseStage.scss
- src/newLaunch/lbp/stages/stage4.html
- src/newLaunch/seed/stages/stage4.html
- src/newLaunch/seed/stages/stage4.ts
needs to be revisited after BE adds aan allow list param
```
const csvContent = this.csv && await this.csv[0].text();
// for BE adds allow list param
// this.launchConfig.launchDetails.allowList = csvContent;
```
with fake label
> Sc 300/add csv upload input to seed details stage

- src/newLaunch/baseStage.scss
- src/newLaunch/seed/stages/stage6.html
- src/newLaunch/seed/stages/stage6.ts
update based on figma design
some values are hardcoded - need to be revisited
> Sc 351/wizard summary update classes feature from

- src/admin/seeds/dashboard/dashboard.html
- src/admin/seeds/dashboard/dashboard.scss
- src/admin/seeds/dashboard/dashboard.ts
- src/entities/Seed.ts
- src/newLaunch/baseStage.scss
- src/newLaunch/launchConfig.ts
- src/newLaunch/lbp/stages/stage4.ts
- src/resources/dialogs/addClass/addClass.html
- src/resources/dialogs/addClass/addClass.scss
- src/resources/dialogs/addClass/addClass.ts
- src/seedSale/seedSale.ts
- src/services/AddClassService.ts
- src/services/TokenTypes.ts
- src/styles/styles.scss
> Sc 335/admin dashboard only mocks add classes functinality

- src/admin/seeds/dashboard/dashboard.ts
Added navigation to the selected seed.
> added navigation to the selected seed dashboard

- src/newLaunch/baseStage.scss
- src/newLaunch/stages/stage8.html
- src/newLaunch/stages/stage8.ts
- src/services/SeedService.ts
- remove tx data field from Thank you page in Wizard>Seed
- create seed
- reach thank you page
- showed data field
- data field gone
> 575 - refac(wizard.seed.thankyou): remove tx data field (used for celo)

- src/newLaunch/seed/stages/stage7.html
- src/newLaunch/stages/stageSixTokenInfo.html
[sc-570]
[sc-572]
fix bugs as described in ticket
> 570, 572 - summary page token address `undefined` and open in new tab

- src/newLaunch/baseStage.scss
- src/newLaunch/seed/stages/stage4.html
- src/newLaunch/seed/stages/stage4.ts
> Sc 580/wizard stage4 white list section needs to

- src/admin/seeds/dashboard/dashboard.ts
- src/entities/Seed.ts
- src/newLaunch/baseStage.scss
- src/newLaunch/seed/stages/stage4.html
- src/resources/dialogs/addClass/addClass.html
- src/resources/dialogs/addClass/addClass.scss
- src/resources/dialogs/addClass/addClass.ts
- src/services/AddClassService.ts
###Updated the following validations in the `addClass` modal:
* ⚠️ ClassCap ≤ HardCAP:
"Please enter a value for Class Purchase limit that is lower or equal to the Funding Tokens Maximum value"
* ⚠️ IndividualCap ≤ HardCAP:
"Please enter a value for Project token Purchase limit that is lower or equal to the Funding Tokens Maximum"
* ⚠️ IndividualCap ≤ ClassCAP:
"Please enter a value for Project token Purchase limit that is lower or equal to the Class Purchase limit value"
* `ClassName` length set to max 50 characters (Added counter to view)
* `Project Token Purchase Limit` can't be empty:
"Please enter a value for project token purchase limit"
* `Vesting Duration` can't be empty:
"Please enter a value for \"Project tokens vested for\" "
* `Vesting Cliff` can't be empty:
"Please enter a …
> Sc 739/admin dashboard add class modal update validation

- src/newLaunch/seed/stages/stage4.ts
Added validations to `seedTip` as described [here](https://www.notion.so/primedao/Prime-Launch-v2-Gherkins-76bf6f6864694ead9c0c56285228266d#1e7657997c4847458873839a0d5ff83c)
> Bug/sc 818/wizard seed details add missing validation

- src/admin/seeds/dashboard/dashboard.html
- src/admin/seeds/dashboard/dashboard.scss
- src/admin/seeds/dashboard/dashboard.ts
Added loading icon when minting (edit/add):
> [feature: sc-965]: Add Loading Icon When Editing Is In Progress

- src/newLaunch/baseStage.scss
- src/newLaunch/stages/stage3.html
> layout fix

- src/resources/dialogs/addClass/addClass.html
- src/resources/dialogs/addClass/addClass.scss
- src/resources/dialogs/dialogs.scss
* Fixed gradient border (NOTE: This change applies app-wide for all the modals! It fixes an issue with the border leaking around the modal body.
* Fixed font size/color/weight
* Fixed `line height` for labels
* Fixed fields and modal width
* Added Cancel button
* Remove Delete button (on edit) - not in the mocks
* Applied new copy for labels and tooltips
* Fixed Class Name max length to 32 (As commented in ticket SC-739)
> Bug/sc 1012/modal adjust pixel perfect to mocks or at

- src/newLaunch/lbp/stages/stage7.html
- src/newLaunch/seed/stages/stage7.html
Fixed unneeded break in stage7 (seed+lbp)
Seed:
LBP:
> [bug/sc-1019]: Unneeded-line-brake-at-thank-you-screen-after

- src/newLaunch/baseStage.scss
Set the cursor to 'not allowed' when hovering toggles in stage 6.
> [bug/sc-1020]: Summary-when-permission-toggle-is-on-should

- src/newLaunch/baseStage.scss
Fixed `I Will Be The Administrator` button alignment in stage 4.
> [bug/sc-1016]: wizard-low-make-me-admin-is-not-centered

- src/admin/seeds/dashboard/dashboard.html
- src/newLaunch/seed/stages/stage6.html
Copy adjustments:
On summary page:
Project token purchase limit (Individual Cap) —> Funding Token Contribution Limit
Contributor class purchase limit (Class Cap) —> Contributor class contribution limit
On the seed dashboard: 
"purchase limit" should be changed to "contribution limit"
> [chore/sc-1238]: renaming-individualcap-and-classcap

- src/services/SeedService.ts
Not 100% sure, if that fixes the underlying issue
> refac(services): Seed: update to what contracts-v2 has

- cypress/fixtures/seedFixtures.ts
- cypress/integration/common/api.e2e.ts
- cypress/integration/common/builders/E2eSeedBuilder.ts
- src/contracts/localhost.json
- src/seedSale/seedSale.ts
- test/unit/services/BigNumberService.spec.ts
- Seed dashboard max buy handling
> Latest seed v2 updates

- src/admin/lbps/dashboard/dashboard.scss
- src/home/home.scss
- src/launches/launches.html
- src/newLaunch/baseStage.scss
- src/newLaunch/permissoned.html
- src/newLaunch/seed/stages/stage4.html
- src/newLaunch/seed/stages/stage6.html
- src/newLaunch/stages/stage3.ts
- src/resources/dialogs/addClass/addClass.scss
- src/resources/elements/sparkChart/spark-chart.ts
- src/resources/elements/timeLeft/timeLeftSeed.html
- src/styles/_colors.scss
> Chore/sc 1912/go through all text copy in the app for seed
